#Range: 0 ~ 100
growingSpeed = 5
#Allowed Values: NO_DROP, INDEPENDENT, ONE_BY_ONE
fruitDropModeSingleplayer = "INDEPENDENT"
#Allowed Values: NO_DROP, INDEPENDENT, ONE_BY_ONE
fruitDropModeMultiplayer = "ONE_BY_ONE"
appleSaplingFromHeroOfTheVillage = true
villageAppleTreeWorldGen = true
fruitTreesWorldGen = true
#Range: 2 ~ 10000
treesGenChunksInPlains = 500
#Range: 2 ~ 10000
treesGenChunksInForest = 200
#Range: 2 ~ 10000
treesGenChunksInJungle = 10

[modules]
	cherry = true
	hybridization = true
	food = true

