
#Settings
[settings]
	#Enable Buildings type from a datapack [true / false]
	enableBuildingsEnd = false
	#Enable Buildings type from a datapack [true / false]
	enableBuildingsNether = false
	#Enable Graveyards type from a datapack [true / false]
	enableGraveyard = false
	#Enable Dungeons type from a datapack [true / false]
	enableDungeon = false
	#Enable Buildings type from a datapack [true / false]
	enableBuildings = false

