#Show HUD compass.
enabled = true
#Position, one of: [TOPLEFT, TOPRIGHT, BOTTOMLEFT, BOTTOMRIGHT]
position = "BOTTOMRIGHT"
#X offset
#Range: -100 ~ 100
offsetX = 3
#Y offset
#Range: -100 ~ 100
offsetY = 3
#The size of the biome info (multiplier)
#Range: 0.5 ~ 2.0
scale = 1.0
#Fields to show. Will display in same order as defined. Options: ["light", "time", "foot", "biome", "season"]
fields = ["light", "time", "foot", "biome", "season"]
#Show text shadow.
textShadow = true
#Label color (Format: #9c9d97)
labelColor = "#9c9d97"
#Label for light level.
lightLabel = "Light: "
#Light color range (Format (dark->bright): #b02e26->#ffd83d)
lightColorRange = "#b02e26->#ffd83d"
#Label for time.
timeLabel = ""
#Time color range (Format (dark->bright): #474f52->#ffd83d)
timeColorRange = "#474f52->#ffd83d"
#Use 12 hour AM/PM display.
timeUse12 = true
#Label for foot level.
footLabel = "Foot level: "
#Foot level color (Format: #5d7c15)
footColor = "#5d7c15"
#Label for biome.
biomeLabel = "Biome: "
#Biome color (Format: #474f52)
biomeColor = "#474f52"
#Compass background opacity.
#Range: 0 ~ 100
compassOpacity = 10

